name: CI for Stock Data Project

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11  # Specify the desired Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Unit Tests
        run: pytest tests

      - name: Check Code Style with Flake8
        run: pip install flake8 && flake8 .

      - name: Check Code Formatting with Black
        run: pip install black && black --check .
